name: Scheduled Data Updates

on:
  schedule:
    # Daily odds update at 8:00 AM EST (13:00 UTC)
    - cron: '0 13 * * *'
    # Score updates on Sunday hourly 10am-9pm EST (15:00-02:00 UTC next day)
    - cron: '0 15-23,0-2 * * 0'
    # Score updates Monday/Thursday 9pm EST (02:00 UTC next day)
    - cron: '0 2 * * 1,5'

jobs:
  update-odds:
    if: github.event.schedule == '0 13 * * *'
    runs-on: ubuntu-latest
    steps:
      - name: Trigger odds update
        run: |
          curl -X POST "${{ secrets.RAILWAY_WEBHOOK_ODDS }}" \
            -H "Content-Type: application/json" \
            -d '{"job": "update_odds"}'

  update-scores:
    if: github.event.schedule != '0 13 * * *'
    runs-on: ubuntu-latest
    steps:
      - name: Trigger score update
        run: |
          curl -X POST "${{ secrets.RAILWAY_WEBHOOK_SCORES }}" \
            -H "Content-Type: application/json" \
            -d '{"job": "update_scores"}'